### PR TITLE
Feature/walk score

### PR DESCRIPTION
**Pull request by gitlyssa**
Completion of the walk score calculation function; there are 5 place categories that (typically) generate 20 places per category. Each place is worth 1% of the total walk score. Calculation uses a DistanceCalculation function which is in a separate java file; but it should be moved to one of the DataAccess files for other uses. Ignore changes to Main.java as it has nothing to do with walk score calculations (updated map code will be in the feature/interactive-map branch which will be done soon)

### CODE REVIEW

**Comment by erinkim16** [comment]
Coding style looks great! There are several comments in the code that describe the purpose, which makes it easier to follow. When I initially ran the code, I got an error for one of the import statements so I wasn't able to run it, but after commenting that part out it worked. It didn't seem like it was being used, so I would just delete it. Also, there was another comment in the console that it failed to load a specific class. I think this might have to do something with the API, so I would check that out. Other than those two things, the code does what it is supposed to do.

**Review by erinkim16 — COMMENTED** [review]
Coding style looks great! The names of different variables and methods are representative of what they are and do. The choices of access modifiers in your code also seem good. There are several comments in the code that describe the purpose, which makes it easier to follow. When I initially ran the code, I got an error for one of the import statements so I wasn't able to run it, but after commenting that part out it worked. It didn't seem like it was being used, so I would just delete it. Also, there was another comment in the console that it failed to load a specific class. I think this might have to do something with the API, so I would check that out. Other than those two things, the code does what it is supposed to do.

**Review by Lucy-426 — COMMENTED** [review]
Overall program looks good and the calculations for walk score look good too! Comments are short but concise and describe what the different parts of the code do pretty well. Variable and constant names are easy to understand and make interpreting the code easier as well. The error and warning that Erin mentioned earlier have also been fixed now so everything is up and running as expected. Just note that there are some merge conflicts so for the future make sure to always pull off of develop and fix any merge conflicts before merging (don't worry about it this time, I'll get it fixed real quick). And, of course as with all of our other PRs, we still need to do some tests. Otherwise, all else looks good, great job with working out the math for the calculations by the way :)

Just leaving a note as a reminder for everyone: As we piece the different components of our entire program together, we'll need to do some refactoring as well to get this code integrated with everything else as we talked about already.

**Review by Lucy-426 — APPROVED** [review]

**Comment by erinkim16** [comment]
I see that the errors have been fixed! Everything looks great now!

**Review by erinkim16 — APPROVED** [review]

**Pull request merged**
